### PR TITLE
Add Google templates

### PR DESCRIPTION
**Pull request by frodenas**
This PR upgrades Bolo release to v0.2.3 and adds Google templates. It also removes the `genesis` binary (it was pretty outdated) and assumes you already have it installed somewhere in your PATH (similar to other genesis *-deployments).

### CODE REVIEW

**Comment by jhunt** [comment]
The genesis binary should be updated, not removed.  It is embedded so that it works with Concourse pipelines.

Either that, or cloning a new deployment needs to embed the calling Genesis.

**Comment by frodenas** [comment]
So why [shield-deployment](https://github.com/starkandwayne/shield-deployment), [concourse-deployment](https://github.com/starkandwayne/concourse-deployment), [vault-deployment](https://github.com/starkandwayne/vault-deployment) & [bosh-lite-deployment](https://github.com/starkandwayne/bosh-lite-deployment) don't have it embedded?

**Comment by frodenas** [comment]
Trying to understand the pattern, I'm a newbie :)

**Comment by geofffranks** [comment]
`genesis` does embed when creating new repos from scratch or via templates, so this shouldn't be a concern.

@frodenas can you fix the merge conflicts and we'll get this merged?

**Comment by frodenas** [comment]
@geofffranks Done.

**Comment by jhunt** [comment]
Thanks!

**Pull request merged**
